### ISSUE TITLE
Error: Permission denied (os error 13) on esp32s3

### ISSUE THREAD

**Issue by lorenzo-pirchio** [jasta/esp32-tokio-demo#7]
Hi,
I'm developing a xmpp client using tokio-xmpp crate for esp32s3 using rust on espidf.
I wrote this in main.rs:

fn main() -> anyhow::Result<(),Error>{
    // It is necessary to call this function once. Otherwise some patches to the runtime
    // implemented by esp-idf-sys might not link properly. See https://github.com/esp-rs/esp-idf-template/issues/71
    esp_idf_svc::sys::link_patches();

    // Bind the log crate to the ESP Logging facilities
    esp_idf_svc::log::EspLogger::initialize_default();

    log::info!("Hello, world!");
    tokio::runtime::Builder::new_current_thread()
      .enable_all()
      .build()?
      .block_on(async move {
        match wifi_connection("x","y").await{
            Ok(()) => {
                println!("Success main ");    
            },
            Err(error) =>{
                println!("{}, main",error);
            },
        };
    });
    Ok(())
}

But I get "Error: Permission denied (os error 13)".
Could it be a problem the use of the existing thread to build the runtime, but esp-idf os doesn't allow me to use that because is managed by esp-idf?

Thanks

**Comment by LelouBil** [comment]
What was the issue ?
